spring:
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: https
      uri: https://localhost:8200
      connection-timeout: 5000
      read-timeout: 15000
      config:
        spring.config.import: vault://
      token: placeholder
