#https://prometheus.io/docs/prometheus/latest/getting_started/
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:8102']
    
    tls_config:
      insecure_skip_verify: true