{
 "title": "API_GATEWAY",
 "time": { "from": "2022-09-02T14:22:36.661Z", "to": "2022-09-02T16:51:38.726Z" },
 "panels": [
  {
   "title": "SYSTEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "PROCESS CPU SECONDS TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PROC UPTIME",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PROCESS CPU USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "process_cpu_usage", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "MISCELLANEOUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP SERV REQ SEC SUM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP SERV REQ SEC MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP SERV REQ SEC CNT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DISK FREE BYTES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "disk_free_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "SPRING CLOUD GATEWAY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "SCG ROUTES CNT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "spring_cloud_gateway_routes_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SCG REQ SEC SUM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SCG REQ SEC CNT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "spring_cloud_gateway_requests_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SCG REQ SEC MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "spring_cloud_gateway_requests_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "KAFKA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "TEMPLATE SECONDS MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "spring_kafka_template_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TEMPLATE SECONDS SUM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "spring_kafka_template_seconds_sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "INCOMING BYTE TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "kafka_producer_incoming_byte_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TEMPLATE SECONDS CNT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "spring_kafka_template_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BATCH SIZE MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      { "expr": "kafka_producer_batch_size_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "INCOMING BYTE RATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "kafka_producer_incoming_byte_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BATCH SIZE AVERAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      { "expr": "kafka_producer_batch_size_avg", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TOPIC BYTE RATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      { "expr": "kafka_producer_topic_byte_rate", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "TOPIC BYTE TOTAL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "kafka_producer_topic_byte_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR RATE RECORD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "kafka_producer_topic_record_error_rate",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CIRCUITBREAKER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "STATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CIRCUITBREAKER BUFFERED CALLS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_buffered_calls",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLOW CALLS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_slow_calls",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CIRCUITBREAKER CALLS SECONDS SUM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_calls_seconds_sum",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NOT PERMITTED CALLS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_not_permitted_calls_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SLOW CALL RATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_slow_call_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CIRCUITBREAKER FAILURE RATE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_failure_rate",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CIRCUITBREAKER CALLS SECONDS MAX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_calls_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CIRCUITBREAKER CALLS SECONDS COUNT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_calls_seconds_count",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}